// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Verify a single BLS12-381 min_pk signature.
///
/// * `sig_bytes` – 96-byte compressed G2 signature
/// * `pk_bytes`  – 48-byte compressed G1 public key
/// * `msg`       – arbitrary-length message
///
/// Returns `true` when the signature is valid, `false` otherwise
/// (including malformed inputs).
bool bls12381MinPkVerify({
  required List<int> sigBytes,
  required List<int> pkBytes,
  required List<int> msg,
}) => RustLib.instance.api.crateApiBlsBls12381MinPkVerify(
  sigBytes: sigBytes,
  pkBytes: pkBytes,
  msg: msg,
);

/// Aggregate multiple BLS12-381 min_pk signatures into one.
///
/// * `sigs_bytes` – list of 96-byte compressed G2 signatures
///
/// Returns the 96-byte aggregate signature, or an empty `Vec<u8>` on error
/// (e.g. empty list, malformed signature).
Uint8List bls12381MinPkAggregate({required List<Uint8List> sigsBytes}) =>
    RustLib.instance.api.crateApiBlsBls12381MinPkAggregate(
      sigsBytes: sigsBytes,
    );

/// Verify an aggregate BLS12-381 min_pk signature where all signers signed
/// the same message.
///
/// * `pks_bytes`     – list of 48-byte compressed G1 public keys
/// * `msg`           – the shared message all signers signed
/// * `agg_sig_bytes` – 96-byte compressed aggregate G2 signature
///
/// Returns `true` when the aggregate signature is valid, `false` otherwise.
bool bls12381MinPkVerifyAggregate({
  required List<Uint8List> pksBytes,
  required List<int> msg,
  required List<int> aggSigBytes,
}) => RustLib.instance.api.crateApiBlsBls12381MinPkVerifyAggregate(
  pksBytes: pksBytes,
  msg: msg,
  aggSigBytes: aggSigBytes,
);
